production:
  adapter: mysql2
  encoding: utf8
  database: <%= Rails.application.secrets.database[:name] %>
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>
  host: db-vpc-shared.cosmytxege6q.us-west-2.rds.amazonaws.com
  port: 3306
